"""remove_dish_id_from_order_items

Revision ID: cd280fc95ac3
Revises: d08e58be916b
Create Date: 2025-12-13 20:06:28.851460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd280fc95ac3'
down_revision: Union[str, None] = 'd08e58be916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_dish_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'dish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_items_dish_id_fkey', 'order_items', 'dishes', ['dish_id'], ['id'])
    # ### end Alembic commands ###
